/**
 * Configuration of all gradle build plugins
 */
object Plugins {
    val androidFeature = "android-feature"
    val commonFeature = "common-feature"
    val commonCoreFeature = "common-core-feature"
    val dynamicFeature = "com.android.dynamic-feature"
    val commonsDynamicFeature = "commons.android-dynamic-feature"
    val updateDependencies = "plugins.update-dependencies"
    val androidConvention = "commons.android-convention"
    val versionCatalog = "commons.version-catalogs"
    val detekt = "plugins.detekt"
    val navigationArgs = "androidx.navigation.safeargs.kotlin"
    val multiplatformResources = "dev.icerock.mobile.multiplatform-resources"
    val googleServices = "com.google.gms.google-services"
    val androidApplication = "com.android.application"
    val androidLibrary = "com.android.library"
    val kotlinKapt = "kotlin-kapt"
    val kotlinAndroid = "kotlin-android"
    val mobileMultiplatform = "dev.icerock.mobile.multiplatform"
    val iosFramework = "dev.icerock.mobile.multiplatform.ios-framework"
    val mavenPublish = "maven-publish"
    val mavenPublishConfig = "publication.maven-publish-config"
    val signing = "signing"
    val swiftPackage = "com.chromaticnoise.multiplatform-swiftpackage"
    val kotlinMultiplatform = "org.jetbrains.kotlin.multiplatform"
    val kotlinSerialization = "kotlinx-serialization"
    val resources = "dev.icerock.mobile.multiplatform-resources"
    val sqldelight = "com.squareup.sqldelight"
    val kotlinParcelize = "kotlin-parcelize"
}
